#!/bin/sh
LC_ALL=C

. "$(dirname "$0")/_/husky.sh"

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feat|fix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"

message="There is something wrong with your branch name.\nBranch names in this project must adhere to this contract: $valid_branch_regex.\nYour commit will be rejected. You should rename your branch to a valid name and try again."
is_invalid_branch_name=0
if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    is_invalid_branch_name=1
fi

yarn lint

if [[ $is_invalid_branch_name =~ 1]]
then
    exit 1
fi

exit 0
